name = "tegworker"
workers_dev = true
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2023-10-01"

[env.production]
workers_dev = false
zone_id = "your-zone-id"
route = "your-domain.com/*"

[[kv_namespaces]]
binding = "voltage"
id = "35d9ba93bccd4316b27a48bc72ceddad"

[triggers]
crons = ["*/5 * * * *"] # This cron expression schedules the worker to run every 5 minutes

