name = "tegworker"
workers_dev = true
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2023-10-01"

[[kv_namespaces]]
binding = "voltage"
id = "35d9ba93bccd4316b27a48bc72ceddad"

[triggers]
crons = ["*/2 * * * *"] # This cron expression schedules the worker to run every 2 minutes

[env.dev]
kv_namespaces = [ 
    { binding = "voltage", preview_id = "b6927a3cebd5481e8f08b27fcb9ca958" }
]
